### ISSUE TITLE
Delete tutorial class does not remove module from list

### ISSUE THREAD

**Issue by mahadhir247** [AY2324S2-CS2103T-T09-4/tp#133]
Not sure if this is intended but if a module only has one class and the class is deleted, the module is not removed from the displayed list.
If this is intended, feel free to close this issue 😸

**Comment by Jajared** [comment]
Yep @mahadhir247 i believe this is the expected behaviour. When creating a new class as well, there will be no teams. Hence , a class can exist without any teams
