### ISSUE TITLE
[PE-D][Tester C] add_student_to_class command not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-4/tp#188]
![image.png](https://raw.githubusercontent.com/dedsecrattle/ped/main/files/166d2ddb-0563-40ca-acc9-cfd09b975d50.png)

There is Module CS2103T and Tutorial T10

and the error feedback is Invalid Command format instead of No such Module exist or Tutorial 

Users is unable to identify what's wrong with their input

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: dedsecrattle/ped#8

**Comment by Jajared** [comment]
The command is supposed to be tutorial/TUTORIAL instead of class/TUTORIAL. This will be resolved in the UG.
