### ISSUE TITLE
[PE-D][Tester D] Unable to view team names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-4/tp#191]
# Description
After randomly allocating team names, I am unable to view the team names, rendering the commands which require team name input unusable. 

While I would normally try to use a view command to view the teams, this would require the team name, which is not viewable by the user. This prevents the user from viewing all team names and using all team related functionalities.

Perhaps this would have to do with the updating of UI components or the internal observable list structure?

## Steps to reproduce
Use the random teams command to randomise team allocation.

## Expected
The user is able to view the teams that were created.

## Actual
The user is unable to view the teams that were created.

## Screenshots
![Screenshot 2024-04-05 at 4.44.41 PM.png](https://raw.githubusercontent.com/itstrueitstrueitsrealitsreal/ped/main/files/ddb78411-681e-44bf-8602-7c11810c5845.png)
![Screenshot 2024-04-05 at 4.47.28 PM.png](https://raw.githubusercontent.com/itstrueitstrueitsrealitsreal/ped/main/files/c4651b06-cdac-45e8-978a-c45d00aa6530.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: itstrueitstrueitsrealitsreal/ped#19

**Comment by Zack-Tay** [comment]
I am not sure about the exact command used to reproduce this issue.
