### ISSUE TITLE
[PE-D][Tester A] Cannot test view teams command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-4/tp#205]
/view_teams name/Team 1 module/CS2103T class/T09 as allocate team command not working. This is quite serious as it is one of the main features of the app. 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Darkarche3/ped#10

**Comment by qinxutan** [comment]
is supposed to be team/T09, will update UG
