### ISSUE TITLE
[PE-D][Tester A] Incorrect name format when adding student

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-4/tp#210]
Can use numbers for names, which should not be possible legally. Even if a number is attached to the name, it is normally Roman numerals by convention.

![Incorrect name format.png](https://raw.githubusercontent.com/Darkarche3/ped/main/files/5a1884e5-395e-4b97-aa81-7510441ff86f.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Darkarche3/ped#13

**Comment by Zack-Tay** [comment]
Feature flaw in the form of regex validation. Will not resolved in this iteration. For planned enhancments.
