### ISSUE TITLE
[PE-D][Tester D] Team size not updated after deletion of student from team

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-4/tp#214]
# Description
After running the delete student from team command, using the view teams command results in an incorrect team member count, hindering the user from managing the teams accurately.

## Steps to reproduce
Delete a student from a team after having added them to the team, and use the view teams command to view the team.

## Expected
The team should have the updated size of the team logged.

## Actual
The team does not have the size updated.

## Screenshots
![Screenshot 2024-04-05 at 5.27.23 PM.png](https://raw.githubusercontent.com/itstrueitstrueitsrealitsreal/ped/main/files/9dca7883-3705-43e1-9d4c-a94977dba997.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: itstrueitstrueitsrealitsreal/ped#25

**Comment by Jajared** [comment]
Team size refers to the maximum size limit of the team here

**Comment by Jajared** [comment]
Change command to team capacity
