### ISSUE TITLE
Add new students' contact

### ISSUE THREAD

**Issue by Zack-Tay** [AY2324S2-CS2103T-T09-4/tp#6]
***User Story***
As a Teaching Assistant (TA), so that I can add new students to the tutorial class.

***Brief description of feature***
This feature allows TAs to add a new student contact with all the details that have been specified by the TA to the relevant module and tutorial class.

Command format: /add_student name/<student_name> email/<student_email> id/<student_id>

***Acceptance criteria***
- [x] The user should be able to add new students contact with complete information.
- [x] The user should not be able to add a student if their student id (which are unique to each student) are already in the system.

**Comment by Jajared** [comment]
Still requires refactoring of command to /add_student
